### ISSUE TITLE
Recordings Won't Go To Recycle Bin/Delete

### ISSUE THREAD

**Issue by GitHubQueenn** [FossifyOrg/Voice-Recorder#41] opened 2024-03-15 21:16 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Voice-Recorder/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Voice-Recorder/issues) or [closed](https://github.com/FossifyOrg/Voice-Recorder/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Voice-Recorder/discussions) or [closed](https://github.com/FossifyOrg/Voice-Recorder/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Voice-Recorder/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 11 on one phone, GrapheneOS Android 14 on another.

### Affected device model

Samsung S20 FE 5G & Pixel 6

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Record.
2. Go to "Player" in the app.
3. Tap & hold on a recording.
4. Press trash bin icon (or 3 dots icon followed by "Select all, and then trash bin icon).
5. Recycle bin is empty and nothing was deleted.

### Expected behavior

Recordings are supposed to be removed to recycle bin, or deleted (depending on settings).

### Actual behavior

Recordings are supposed to be removed to recycle bin, or deleted (depending on settings).

They are not.

### Screenshots/Screen recordings

https://i.imgur.com/DbEX2BY.mp4

### Additional information

This also happens with the original Simple Recorder app and, yes, I changed recording directory where the recordings get saved, so that is proper as well. Also, I see the similar bug report [under this report](https://github.com/FossifyOrg/Voice-Recorder/issues/40), but mine is more insightful, uses proper spelling/grammar/punctuation, and includes a video example, so theirs can be closed/deleted so you can just keep this one.

**Comment by Aga-C** [comment] 2024-03-15 21:21
It's a duplicate of https://github.com/FossifyOrg/Voice-Recorder/issues/40.

**Comment by GitHubQueenn** [comment] 2024-03-15 21:22
> It's a duplicate of #40.

I see the similar bug report [under this report](https://github.com/FossifyOrg/Voice-Recorder/issues/40), but mine is more insightful, uses proper spelling/grammar/punctuation, and includes a video example, so theirs can be closed/deleted so you can just keep this one.

**Closed by Aga-C** 2024-03-15 21:21 UTC
Labels: bug, needs triage

**Comment by GitHubQueenn** [comment] 2024-03-16 20:11
> It's a duplicate of #40.

Yo, I replied to you, don't ignore me. Mine is *way* better than #40 and actually proper.
